### ISSUE TITLE
Production use case not valid for Now 2.0?

### ISSUE THREAD

**Issue by r0mflip** [vercel/serve-handler#105]
I've tried to use [the production use case](https://github.com/zeit/serve-handler#production) for a site I was testing using Now 2.0 with GitHub integration.

But the Now bot commented that the `static` property cannot be used in the config and the build failed. The option cannot be seen in https://zeit.co/docs/configuration too, so is it invalid?

**Comment by r0mflip** [comment]
Can anyone confirm this?

**Comment by TooTallNate** [comment]
Sorry for the late reply. That section of the Readme did indeed only apply to Now 1.0, and this module isn't necessary with the v2.0 platform, because 2.0 supports static files as a first class citizen and an external module like this one is not necessary. And for local development, the `vercel dev` command should be used instead of `server.

As such, I've removed that section of the Readme at this time.
